### ISSUE TITLE
npm package out of date

### ISSUE THREAD

**Issue by xob** [vinta/hubot-reload-scripts#6]
The current package version on npm is 0.1.2, whereas the most recent version in your recent commit (5 days ago, at the time of this writing) is 0.1.4.

I was trying to debug why my external script wasn't reloading properly, and I was looking at your code wondering why the code I was seeing wasn't working, until I noticed the version discrepancy.

**Comment by vinta** [comment]
My fault, I will publish the newer version later.

**Comment by vinta** [comment]
@xob Done! Please check out https://www.npmjs.com/package/hubot-reload-scripts
